<script lang="ts">
	import Question from '$lib/question.svelte';
	import Summary from '$lib/summary.svelte';
	import { page } from '$app/stores';
	import { tea_fill, tea_level } from '$lib/stores';

	import JSON5 from 'json5';

	let subject;
	let topic;

	let question = null;

	let chat_gpt_out = null;

	let generating = false;

	async function on_fail() {
		alert('ChatGPT produced invalid output.');

		generating = false;
		chat_gpt_out = [];
		answer = null;
	}

	async function send_req() {
		console.log(answer);

		generating = true;

		question["information"] = "This question was generated by ChatGPT, so it may not exactly replicated a GCSE question. Factor this in when you are marking. Be VERY lenient, and scale the amount of marks that the student should get upwards because ChatGPT has a tendency to generate questions with too many marks!";

		chat_gpt_out = await fetch(`${$page.url}/mark`, {
			method: "PUT",
			body: JSON.stringify({ question, answer })
		})
			.then(t => t.text())
			.then(t => JSON5.parse(t))
			.catch(on_fail);
		generating = false;

		fill_tea()
	}

	function fill_tea() {
		for(let output of chat_gpt_out) {
			tea_fill.update(t => t + output.mark * Math.floor(25 / $tea_level))
		}
	}

	async function get_question() {
		generating = true;
			question = await fetch(`/generator?subject=${subject}&topic=${topic}`)
				.then(async t => t.json())
				.then(t => JSON5.parse(t))
				.catch(on_fail);
		generating = false;

		chat_gpt_out = null;
	}

	let answer: any;
</script>

<main class="flex flex-col items-center justify-center w-screen h-screen overflow-y-auto overflow-x-hidden">
	<h2>Please input a GCSE topic that you'd like to be quizzed about</h2>
	<input type="text" name="subject" id="subject" bind:value={subject} placeholder="Subject..." class="my-2.5 p-3 text-lg border-4 border-black rounded-xl w-96">
	<input type="text" name="topic" id="topic" bind:value={topic} placeholder="Topic..." class="my-2.5 p-3 text-lg border-4 border-black rounded-xl w-96">
	<button on:click={get_question} class="bg-emerald-300 p-4 rounded-xl w-96">Generate Question</button>

	{#if generating}
	<h2>Please wait while we generate...</h2>
	{:else}
	{#if question}
		{#if chat_gpt_out}
			{#each chat_gpt_out as output, idx}
				<Summary chat_gpt_out={output} {question} {idx} />
			{/each}
		{:else}
				<Question {question} bind:answer mark={send_req} />
		{/if}
	{/if}
	{/if}
</main>